apiVersion: apps/v1
kind: Deployment
metadata:
  name:  keycloack
  labels:
    app:  keycloack
spec:
  selector:
    matchLabels:
      app: keycloack
  replicas: 1
  template:
    metadata:
      labels:
        app:  keycloack
      annotations:
        repo: n/a
        swagger: n/a
    spec:
      containers:
      - name: keycloack
        image:  quay.io/keycloak/keycloak:21.1.1
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloack-nodeport
spec:
  type: NodePort
  selector:
    app: keycloack
  ports:
    - port: 8080
      targetPort: 8080