apiVersion: apps/v1
kind: Deployment
metadata:
  name:  springbootdemo-keycloak
  labels:
    app:  springbootdemo-keycloak
spec:
  selector:
    matchLabels:
      app: springbootdemo-keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app:  springbootdemo-keycloak
      annotations:
        repo: n/a
        swagger: n/a
    spec:
      containers:
      - name: springbootdemo-keycloak
        image:  mzavaletav/springboot-keycloak-demo:1.2
        env:
        - name: keycloak__url-base
          value: http://10.107.19.11:8080
        - name: keycloak__client-id
          value: myclient
        - name: keycloak__grant-type
          value: password
        - name: keycloak__realm-id
          value: testrealm
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springbootdemo-keycloak-nodeport
spec:
  type: NodePort
  selector:
    app: springbootdemo-keycloak
  ports:
    - port: 8080
      targetPort: 8080